name: Build and Upload

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        npm i
        npm install electron-packager --save-dev

    - name: Build
      run: npm run packager

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: electron-build
        path: ./dist

