name: Build and Upload

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Wine
      run: sudo apt-get install wine64
    
    - name: Install Dependencies
      run: |
        npm i
        npm install electron-packager --save-dev

    - name: Build
      run: npm run packager

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: NeuvilletteQuickStart_build
